### ISSUE TITLE
[issue] Controller is required

### ISSUE THREAD

**Issue by ZoneTwelve** [ZoneTwelve/exprango#1]
Sometimes, my application only needs a Router can simply route the net-flow, but I got this error without a controller

```javascript
...
root['self'] = config['control'].complete( {name, allowPrivate: true} );
...

TypeError: Cannot read properties of undefined (reading 'complete')
    at createModule (/code/figerlight/node_modules/expjango/lib/application.js:33:36)
    at ModularContainer.createModule (/code/figerlight/node_modules/expjango/lib/application.js:12:38)
    at Function.app.modular (/code/figerlight/node_modules/expjango/lib/extension.js:18:40)
    at Object.<anonymous> (/code/figerlight/app.js:28:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)

```

and it's my package.json
```json
{
  "name": "application",
  "version": "...",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "cookie-parser": "~1.4.4",
    "debug": "~2.6.9",
    "ejs": "^3.1.8",
    "expjango": "^0.0.0",
    "express": "~4.16.1",
    "http-errors": "~1.6.3",
    "morgan": "~1.9.1"
  }
}
```

**Comment by ZoneTwelve** [comment]
Hi, this issue will fix in the next update.

**Comment by ZoneTwelve** [comment]
fix on the latest release
https://github.com/ZoneTwelve/exprango/commit/35d44d1660d7be45b55825bb8053da26a9d3dc93
